### PR TITLE
Fix search filter on Firefox

### PR DESCRIPTION
**Pull request by marcioAlmada**
```TypeError: t.innerText is undefined```

Fix buggy search filter on Firefox, just the minimum changes. Still works on Chrome >> http://quirksmode.org/dom/html/#t01

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
`toLowerCase` is redundant, that's what the `i` regex modifier is for ;-)

**Comment by hannesvdvreken** [comment]
Also the link says to use this for browsers compat:

```js
var text = row.textContent || row.innerText;
```

**Comment by Anahkiasen** [comment]
> Also the link says to use this for browsers compat:

**Comment by marcioAlmada** [comment]
Updated ^^

**Comment by hannesvdvreken** [comment]
:+1:

**Pull request merged**
